name: ss_experience
dependencies:
  over_react: ">=2.0.0 <4.0.0"
dev_dependencies:
  build_runner:
  build_test:
  build_web_compilers:

dependency_overrides:
  shell_events:
    path: ../shell_events
  react:
    git:
      url: git@github.com:cleandart/react-dart.git
      ref: 5.1.0-wip
  over_react:
    git:
      url: git@github.com:Workiva/over_react.git
      ref: 3.1.0-wip
